export const albums = {
  '01': [
    'post/01/clouds-1.jpg',
    'post/01/clouds-2.jpg',
    'post/01/clouds-3.jpg',
    'post/01/shack.jpg',
    'post/01/sunrise.jpg',
    'post/01/buddha-statue.jpg',
    'post/01/TaVan-1.jpg',
    'post/01/TaVan-3.jpg',
    'post/01/TaVan-4.jpg',
    'post/01/TaVan-5.jpg',
    'post/01/cafe.jpg'
  ],
  '02': [
    'post/02/blue.jpg',
    'post/02/after-rain.jpg',
    'post/02/cozy.jpg',
    'post/02/in-the-city.jpg',
    'post/02/morning.jpg',
    'post/02/vintage.jpg',
    'post/02/light-bulb.jpg',
    'post/02/sun-set.jpg',
  ],
  '03': [
    'post/03/kanaoshi.jpg',
    'post/03/midnight-lamp.jpg',
    'post/03/afternoon.jpg',
    'post/03/balcony.jpg',
    'post/03/vegetables.jpg',
  ],
  '04': [
    'post/04/aged-building.jpg',
    'post/04/aged-library.jpg',
    'post/04/pictures.jpg',
    'post/04/building.jpg',
    'post/04/cyclo.jpg',
    'post/04/trang-tien.jpg',
    'post/04/lucky-cat.jpg',
    'post/04/balloons.JPG',
    'post/04/flower.jpg',
    'post/04/flowers-1.JPG',
    'post/04/flowers-2.JPG',
    'post/04/horse-plant.JPG',
    'post/04/cháu.jpg',
    'post/04/illustrator.JPG',
    'post/04/racin.JPG',
    'post/04/skatin.JPG',
  ],
  '05': [
    'post/05/alone.jpg',
    'post/05/balloons.jpg',
    'post/05/bánh-tráng-nướng.jpg',
    'post/05/bubbles.jpg',
    'post/05/exhibition.jpg',
    'post/05/ice-cream.jpg',
    'post/05/playin.jpg',
    'post/05/red.jpg',
    'post/05/shinhan-digital-dove.jpg',
    'post/05/ramen-shop.jpg',
  ]
}